### ISSUE TITLE
Sleep Analysis: HKCategoryTypeIdentifierSleepAnalysis

### ISSUE THREAD

**Issue by anthonycl** [Telerik-Verified-Plugins/HealthKit#13]
Is there a way to get sleep analysis data with querySampleType. I think some modifications might need to be made. I can't find the unit type to put in the request.

**Comment by kingsfleet** [comment]
You can use querySampleType as category type is a subtype of sample type. I have used this successfully.

**Comment by anthonycl** [comment]
So can you give me an example of how you used querySampleType to get sleepAnalysis. I assume I use 'HKCategoryTypeIdentifierSleepAnalysis' as sampleType but what do I put for unit?

**Comment by kingsfleet** [comment]
I wrote this up just in case, no units required. 

http://kingsfleet.blogspot.co.uk/2015/02/how-long-did-i-sleep-last-night-using.html
