### ISSUE TITLE
Adding save for blood pressure and heart rate

### ISSUE THREAD

**Issue by H0rst** [Telerik-Verified-Plugins/HealthKit#14]
Hello,

i would like to be able to save blood pressure and heart rate to Healthkit.

best regards
Horst

**Comment by H0rst** [comment]
Maybe it would be possible to make a function like this:

window.plugins.healthkit.save(
  {
    'requestReadPermission':false, 
    'type'  : 'HKQuantityTypeIdentifierHeartRate', 
    'unit'  : 'count/min', 
    'amount': 60,
    'date'  : new Date()
  },
  onSuccess,
  onError
);

It is just a copy from your documentation for saveWeight, only extended with the "type" parameter.

best regards
Horst

**Comment by kapilgwb** [comment]
We have used this code, buit this is not working for heart rate and blood pressure both.
Please suggest me, what function we can use for save heart rate and blood pressure details to aplle healthkit.
