### ISSUE TITLE
Wish: Changing and deleting

### ISSUE THREAD

**Issue by H0rst** [Telerik-Verified-Plugins/HealthKit#16]
Is it possible to change a entry or delete it?

**Comment by EddyVerbruggen** [comment]
I'll look into this. Good suggestion!

**Comment by bcfchen** [comment]
+ 1. It'd be great to include full CRUD operations

**Comment by H0rst** [comment]
Any news?

**Comment by H0rst** [comment]
Is the plugin dead? Can i do something to help?

**Comment by EddyVerbruggen** [comment]
Not dead at all, just not quite clear on the requirement I guess so please specify what you need exactly (in a new issue, with details on which data you want to alter exactly), or perhaps something useful has been implemented in the meanwhile which serves your needs.
