### ISSUE TITLE
Wish: Determine activity type

### ISSUE THREAD

**Issue by bcfchen** [Telerik-Verified-Plugins/HealthKit#17]
Is there a way to have findWorkouts() return activityType associated with each activity? i.e. walking, running...etc.

**Comment by EddyVerbruggen** [comment]
Working on this.. it will return the iOS activityTypes (HKWorkoutActivityTypeClimbing, etc).

**Comment by bcfchen** [comment]
Great!! Please keep me posted. Looking forward to this. It may also be useful to provide the calories too for each workout object

**Comment by EddyVerbruggen** [comment]
Hi, you can now use v 0.3.1 which returns the `activityType` in the `findWorkouts` response.

I've added a TODO in the code for the `totalEnergyBurned` property. Will add it later probably.

**Comment by bcfchen** [comment]
Thanks! I'll give it a shot
