### ISSUE TITLE
monitorSampleType in background thread

### ISSUE THREAD

**Issue by stevenvegt** [Telerik-Verified-Plugins/HealthKit#19]
I'm experimenting with your nice Healthkit plugin and the (experimental) monitorSampleType method.
I've got things working, but encountered the following line in my logs:

THREAD WARNING: ['HealthKit'] took '62985.450195' ms. Plugin should use a background thread.

Found this thread on Stackoverflow which provides a little context:
http://stackoverflow.com/questions/20370598/thread-warnings-in-phonegap-cordova-app

I'm not an Objective-C expert, do you think that some code needs wrapping in a background job?

**Comment by EddyVerbruggen** [comment]
Hi, yes that would be the way to go, but it shouldn't harm your app. I'll leave this open to pick up one day. Thanks for reporting it.

**Comment by EddyVerbruggen** [comment]
Just to note: I've just updated `monitorSampleType` to more reliably notify your app of background updates. Available in 0.3.7.
