### ISSUE TITLE
Workout Duration in Milliseconds?

### ISSUE THREAD

**Issue by gylippus** [Telerik-Verified-Plugins/HealthKit#20]
Hey Eddy, 

iOS 8.2 added the ability to actually view workout activities as "Trainings" in hours/minutes rather than just the Active Calories burned. 

I believe that the demo mentioned that the duration for saveWorkout and then in line 121 of HealthKit.m it calculates the duration when an endDate is not given. Could you confirm that this is adding it to a millisecond date value? 

If so, I think the only real thing that needs to be done would be to update the demo index.html to say milliseconds instead of seconds next to duration. 

Does this sound about right? We only noticed because a user said their 5 minute workout showed up as 8 seconds.

**Comment by EddyVerbruggen** [comment]
Hi, it's actually in seconds, see this debugging screenshot of XCode 6.2, running on my iPhone 6 /w iOS 8.2:

![schermafbeelding 2015-03-12 om 16 47 00](https://cloud.githubusercontent.com/assets/1426370/6621579/b152f264-c8d7-11e4-9d05-af5d3f70e43e.png)

Can you send me the JS code you used to save the workout?

**Comment by gylippus** [comment]
Admittedly I'm not 100% up to date with the latest version, but here is what I am using:

```
var startDate = new Date(); //This is created at the beginning of the workout
var minutesCompleted = 5;
var energyBurn = 40;
window.plugins.healthkit.saveWorkout({
	 'activityType': 'HKWorkoutActivityTypeFunctionalStrengthTraining',
	 'quantityType': null,
	 'startDate': $scope.startDate,
	 'endDate': null,
	 'duration': minutesCompleted * 60,
	 'energy': energyBurn,
	 'energyUnit': 'kcal',
	 'distance': null,
	 'distanceUnit': 'm'
	 },
	 function(msg){
	  console.log('HealthKit success: ' + msg);
	 },
	 function(msg){
	  console.log('HealthKit error: ' + msg);
	 }
);
```
Doesn't startDate.timeIntervalSince1970 in line 121 of what is in mater now return milliseconds though which we are then adding seconds to? 

I do need to test on the updated Health.m file though, but I was just curious that it seemed like it was subtracting seconds from milliseconds. I am still on this old code:

```
    int duration = 0;
    NSNumber* startTime  = [args objectForKey:@"startTime"];
    NSTimeInterval _startInterval = [startTime doubleValue] / 1000; // strip millis
    NSDate *startDate = [NSDate dateWithTimeIntervalSince1970:_startInterval];
    
    NSDate *endDate;
    if ([args objectForKey:@"duration"]) {
        duration = [[args objectForKey:@"duration"] intValue];
        endDate = [NSDate dateWithTimeIntervalSince1970:_startInterval + duration];
    } else if ([args objectForKey:@"endTime"]) {
        NSNumber* endTime = [args objectForKey:@"endTime"];
        NSTimeInterval _endInterval = [endTime doubleValue] / 1000; // strip millis
        endDate = [NSDate dateWithTimeIntervalSince1970:_endInterval];
    } else {
        CDVPluginResult* result = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsString:@"no duration or endDate was set"];
        [self.commandDelegate sendPluginResult:result callbackId:command.callbackId];
        return;
    }
```

**Comment by EddyVerbruggen** [comment]
`timeIntervalSince1970` is in seconds so it must be something else. Please update and let me know what you find out..

**Comment by gylippus** [comment]
Thanks for the verification Eddy, I put some breakpoints into Xcode and it is a mistake on my part for what I am passing in minutes. Never really mattered until 8.2 so I never really saw the time an output.

**Comment by EddyVerbruggen** [comment]
:+1:

**Comment by desmeit** [comment]
@gylippus I tested your code with version 0.5.6 but its not working. I get:

*** Terminating app due to uncaught exception '_HKObjectValidationFailureException', reason: 'Invalid data type (null)'

@EddyVerbruggen Do you have an Idea? I tried exactly the same code like gylippus.
