### ISSUE TITLE
Question: Check which permissions are enabled by user

### ISSUE THREAD

**Issue by bcfchen** [Telerik-Verified-Plugins/HealthKit#23]
Hi! I was wondering if it might be possible to check which permissions are actually enabled by the user via the HealthKit's permissions screen? I'm currently calling the request authorization method like:

            $cordovaHealthKit.requestAuthorization(
                permissions, // Read permission
                permissions // Write permission
            ).then(function(success) {
                // store that you have permissions
                console.log("success! " + success);
            }, function(err) {
                console.log("error! " + err);
            });

I noticed that even when the user doesn't enable any permissions on the permissions page and simply hit "done", it still enters the success callback function, and the "success" object is null. Is there a way to check if the user actually enabled permissions?

Thanks a ton!

**Comment by EddyVerbruggen** [comment]
Hi, excellent question!

I just added a new function: `checkAuthStatus`. [See the demo](https://github.com/Telerik-Verified-Plugins/HealthKit/blob/master/demo/index.html) for usage details.

Each type is either `undetermined`, `denied`, or `authorized`, so I thought it'd be easiest you could simply pass in one `type`.

Please let me know what you think.

**Comment by bcfchen** [comment]
Cool! I think this will work. I'll give it a shot tonight and let you know how it goes :) Thanks a ton!

**Comment by bcfchen** [comment]
I just re-installed my Healthkit cordova plugin and gave it a shot. Strangely enough, I'm getting this error message:

22    352234   error    Error: undefined is not a function (evaluating '$cordovaHealthKit.checkAuthStatus')
requestAuthorization@http://192.168.1.9:8100/app/services/healthKit/healthKitApi.js:81:46

I'm making the call like:
            $cordovaHealthKit.checkAuthStatus({
                    'type': 'HKQuantityTypeIdentifierDistanceWalkingRunning'
                }, function(response){
                        alert(JSON.stringify(response));
                        deferred.resolve(response);
                });

The weird thing is, in my HealthKit.m, I'm actually seeing this:

- (void) checkAuthStatus:(CDVInvokedUrlCommand*)command {

So the function does seem to exist. Would you have any idea where else I might check?

Thanks a bunch!

**Comment by EddyVerbruggen** [comment]
I added the function to the plugin, not to ngCordova.

**Comment by EddyVerbruggen** [comment]
For your convenience, I just added `checkAuthStatus` to ngCordova: https://github.com/driftyco/ng-cordova/pull/753

Please wait until it's released, or go bleeding edge.

**Comment by bcfchen** [comment]
Ahhh no duh, how embarrassing :( Thanks a bunch!
