### ISSUE TITLE
saveWorkout function issue

### ISSUE THREAD

**Issue by kapilgwb** [Telerik-Verified-Plugins/HealthKit#24]
Your document says that distance is optional but when i comment this line then it creates exception. And also please tell me which identifier should be used for dancing, fishing etc. workout.

Thanks in advance.

**Comment by EddyVerbruggen** [comment]
Hi, well spotted, thanks!

It's really optional now :)

**Comment by flexed** [comment]
Your hotfix was unnecessary. Energy is optional and works with the != nil syntax.

**Comment by EddyVerbruggen** [comment]
Fair point, but it did indeed error with != nil and did not with the updated code when I tested this today. Still, energy should behave the same so I'm reopening this.

**Comment by EddyVerbruggen** [comment]
Put this baby to bed in version 0.3.7.
