### ISSUE TITLE
querySampleType and sumQuantityType functions not working

### ISSUE THREAD

**Issue by derulo** [Telerik-Verified-Plugins/HealthKit#26]
Hello Eddy,
I just played with the plugin and all functions work properly (read/save Weight/Height) except the querySampleType and sumQuantityType function. I don't get any response from those functions whatsoever (nor onSuccess, not onError). What could be wrong or where should I be looking? I just upgraded to iOS 8.3, I haven't tried it on earlier version though, so I was thinking if this is perhaps an issue.
Using phonegap-version 3.7.0 and I include the plugin in config.xml using gap:plugin name="com.telerik.plugins.healthkit"

**Comment by derulo** [comment]
It seems it is due to an old version of the plugin. I just checked in the PhoneGap Build and it's showing plugin version 0.1.0 whereas the latest HealthKit version on github is 0.3.3. How can I use the latest version in Phonegap? I tried to put version="0.3.3" in config.xml but that didn't fly.

**Comment by EddyVerbruggen** [comment]
Hi, can you try again, but also add `src="plugins.cordova.io"` to the tag?

**Comment by derulo** [comment]
HI, it's the same result. I checked in the Plugin section after building and it's still showing version 0.1.0 and as source "pgb"

**Comment by derulo** [comment]
Hi Edi, I just found on the PhoneGap Build website that the correct attribute to include a plugins.cordova.io plugin is source="...". Will try it later and will let you know

http://docs.build.phonegap.com/en_US/configuring_plugins.md.html

**Comment by EddyVerbruggen** [comment]
Correct.

Note to self: don't rely on memory- look things up. 
Now where do I store this advice...

**Comment by derulo** [comment]
Repeat it loud three times, then you will most probably remember forever :-) Thanks for your hints, just tried it and it works! Is there a way to write sampleTypes (i.e. nutrition values) in a similar way like reading them?

**Comment by EddyVerbruggen** [comment]
Thanks for the tip ;)

Your question will be convered in #22 which I need to find a bit of time for.

**Comment by derulo** [comment]
Hello,
It seems that the version 0.3.4. is not yet available on plugins.cordova.io, was trying to integrate it with phonegap yesterday. I could see there version 0.3.3.
Thanks for help!

**Comment by EddyVerbruggen** [comment]
@derulo good call, it's up there now.

**Comment by derulo** [comment]
I just tested it but it hangs on start of the app before even calling any of the methods. When switching back to version 0.3.3 it works again.

**Comment by EddyVerbruggen** [comment]
@derulo can I have a look at your code? My test project behaves as before..

**Comment by derulo** [comment]
I found that JavaScript throws an error:
"module com.telerik.plugins.healthkit.Healthkit already defined."
