### ISSUE TITLE
Add correlation type query and save

### ISSUE THREAD

**Issue by sgilroy** [Telerik-Verified-Plugins/HealthKit#29]
Please add methods to query and save a correlation (such as systolic and diastolic blood pressure).

https://github.com/CrossComm/HealthKit/commit/6d29abeb768da881d4016cd38ae9890ee8f9d3ea

**Comment by EddyVerbruggen** [comment]
Hi, see #31 which resulted in the new 0.3.4 version.

To assist you with these new features I've created [a few examples](https://github.com/Telerik-Verified-Plugins/HealthKit/blob/master/demo/index.html#L271-L314).

Enjoy!
