### ISSUE TITLE
Issue building HealthKit with latest Xcode?

### ISSUE THREAD

**Issue by kingsfleet** [Telerik-Verified-Plugins/HealthKit#32]
Odd one, just updated to 0.3.3 using the command line tools, and the project no longer compiles, instead fails with the following linkage errors:

Ld /Users/gdavison/Library/Developer/Xcode/DerivedData/KeepingWell-aodgojqbwmyfysckkigmmvwotzpc/Build/Products/Debug-iphonesimulator/KeepingWell.app/KeepingWell normal x86_64
    cd /Users/gdavison/Development/NetBeansProjects/Monitor/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=7.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk -L/Users/gdavison/Library/Developer/Xcode/DerivedData/KeepingWell-aodgojqbwmyfysckkigmmvwotzpc/Build/Products/Debug-iphonesimulator -F/Users/gdavison/Library/Developer/Xcode/DerivedData/KeepingWell-aodgojqbwmyfysckkigmmvwotzpc/Build/Products/Debug-iphonesimulator -filelist /Users/gdavison/Library/Developer/Xcode/DerivedData/KeepingWell-aodgojqbwmyfysckkigmmvwotzpc/Build/Intermediates/KeepingWell.build/Debug-iphonesimulator/KeepingWell.build/Objects-normal/x86_64/KeepingWell.LinkFileList -Xlinker -objc_abi_version -Xlinker 2 -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -force_load /Users/gdavison/Library/Developer/Xcode/DerivedData/KeepingWell-aodgojqbwmyfysckkigmmvwotzpc/Build/Products/Debug-iphonesimulator/libCordova.a -ObjC -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=7.1 -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/gdavison/Library/Developer/Xcode/DerivedData/KeepingWell-aodgojqbwmyfysckkigmmvwotzpc/Build/Intermediates/KeepingWell.build/Debug-iphonesimulator/KeepingWell.build/KeepingWell.app.xcent -framework AssetsLibrary /Users/gdavison/Library/Developer/Xcode/DerivedData/KeepingWell-aodgojqbwmyfysckkigmmvwotzpc/Build/Products/Debug-iphonesimulator/libCordova.a -framework CoreGraphics -framework MobileCoreServices -framework CoreLocation -weak_framework AudioToolbox -weak_framework Social -weak_framework MessageUI -framework StoreKit -lz -liconv -framework AVFoundation -framework CoreVideo -framework QuartzCore -Xlinker -dependency_info -Xlinker /Users/gdavison/Library/Developer/Xcode/DerivedData/KeepingWell-aodgojqbwmyfysckkigmmvwotzpc/Build/Intermediates/KeepingWell.build/Debug-iphonesimulator/KeepingWell.build/Objects-normal/x86_64/KeepingWell_dependency_info.dat -o /Users/gdavison/Library/Developer/Xcode/DerivedData/KeepingWell-aodgojqbwmyfysckkigmmvwotzpc/Build/Products/Debug-iphonesimulator/KeepingWell.app/KeepingWell

Undefined symbols for architecture x86_64:
  "_HKSampleSortIdentifierEndDate", referenced from:
      -[HKHealthStore(AAPLExtensions) aapl_mostRecentQuantitySampleOfType:predicate:completion:] in HKHealthStore+AAPLExtensions.o
  "_OBJC_CLASS_$_HKHealthStore", referenced from:
      l_OBJC_$_CATEGORY_HKHealthStore_$_AAPLExtensions in HKHealthStore+AAPLExtensions.o
  "_OBJC_CLASS_$_HKSampleQuery", referenced from:
      objc-class-ref in HKHealthStore+AAPLExtensions.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is this an error anybody else has come accross?

**Comment by kingsfleet** [comment]
Forgot to add HealthKit framework, odd I thought I would have had this from a previous version

**Comment by wesleygauntt** [comment]
Just an update for anyone else running in to this-

As of version 0.3.5 I needed not only to add the Healthkit framework to Xcode (Build Phases > Link Binary with Libraries), but to also add Healthkit.m AND WorkoutActivityConversion.m to my Compile Sources (Build Phases > Compile Sources)
