### ISSUE TITLE
Add support for collection queries (HKStatisticsCollectionQuery)

### ISSUE THREAD

**Issue by InfloErik** [Telerik-Verified-Plugins/HealthKit#33]
HKStatisticsCollectionQuery would enable retrieving daily data for steps, calories, etc. This can be accomplished using sumQuantityType() but only for a single day. According to apple "collection queries can also receive updates when matching samples are added to or removed from the HealthKit store.

**Comment by yowakita** [comment]
Has there been any updates since this issue was opened? I am looking to have the same feature as InfloErik, thanks!

**Comment by OleksandrPoltavets** [comment]
Any updates on this so far ? It would be nice to retrieve such data especially for steps.

**Comment by EddyVerbruggen** [comment]
With 0.4.0 you now can retrieve aggregated hourly and daily data, [see this little demo](https://github.com/Telerik-Verified-Plugins/HealthKit/blob/master/demo/index.html#L239-L251)
