### ISSUE TITLE
Extra shim on the plugin. Causing cordova to think plugin already exists.

### ISSUE THREAD

**Issue by hdavidzhu** [Telerik-Verified-Plugins/HealthKit#36]
```
0     923650   error    module com.telerik.plugins.healthkit.HealthKit already defined, http://<host>/cordova.js, Line: 71
1     928421   log      deviceready has not fired after 5 seconds.
2     928424   log      Channel not fired: onCordovaReady
3     928426   log      Channel not fired: onCordovaInfoReady
```

This error is caused by the following line 1-2 in [HealthKit.js](https://github.com/Telerik-Verified-Plugins/HealthKit/blob/8742a4fa9798e621ebb74ec94f530504bf0e9175/www/HealthKit.js#L1):
```
cordova.define("com.telerik.plugins.healthkit.HealthKit", function(require, exports, module) { function HealthKit() {
```

This is added from 0.3.3 to 0.3.4. However, during the build process of Ionic (Cordova), an additional cordova.define is created, causing the plugin to be unusable.

**Comment by hdavidzhu** [comment]
@EddyVerbruggen I messed up. I forgot to delete the trailing parenthesis on the last line. [HealthKit.js](https://github.com/Telerik-Verified-Plugins/HealthKit/blob/8742a4fa9798e621ebb74ec94f530504bf0e9175/www/HealthKit.js#L270) is still broken. Would you be willing to resolve this and make 0.3.4 functional again? Sorry for the trouble.

**Comment by EddyVerbruggen** [comment]
No worries, I merged this while on the road, I'll fix this right now.

**Comment by EddyVerbruggen** [comment]
0.3.4 retagged.
