### ISSUE TITLE
Denied status for accepted ReadTypes

### ISSUE THREAD

**Issue by mansa-dev** [Telerik-Verified-Plugins/HealthKit#38]
I have these read types -

`['HKQuantityTypeIdentifierBodyMass','HKQuantityTypeIdentifierStepCount','HKQuantityTypeIdentifierHeartRate']`

Plugin is able to pull the data and read it. It works great. But if run `checkAuthStatus` like this -

 `window.plugins.healthkit.checkAuthStatus({
                  type : "HKQuantityTypeIdentifierBodyMass"
                },console.log,console.log);`

it always return `denied` even if the permissions are granted.

Platform : iOS 8.3

**Comment by mansa-dev** [comment]
It appears its not plugins fault. I think we need the write permission to access permission status on Healthkit. I will test it today.

**Comment by mansa-dev** [comment]
It works if we have the write permissions. Thanks for the great plugin :)

**Comment by ianisted** [comment]
Is there a way to check permission for reading only? I'm not currently relying on writing data, so wouldn't want to ask permission for writing just to get the authStatus. It also wouldn't be very accurate if the use decided against writing but allowed reading.

Any ideas?

**Comment by EddyVerbruggen** [comment]
@ianisted Check [this official doc](https://developer.apple.com/library/ios/documentation/HealthKit/Reference/HKHealthStore_Class/index.html#//apple_ref/occ/instm/HKHealthStore/authorizationStatusForType:) @ 'discussion'

**Comment by ianisted** [comment]
Thanks @EddyVerbruggen. Just found and was going to post it. Damn that's frustrating.
