### ISSUE TITLE
querySampleType only returning single day

### ISSUE THREAD

**Issue by zpeterg** [Telerik-Verified-Plugins/HealthKit#41]
When I query a date range for most sample types using querySampleType (eg., HKQuantityTypeIdentifierActiveEnergyBurned), the return is less than a full day of data. The exception seems to be HKQuantityTypeIdentifierStepCount, which will return up to 4-5 days of data.

I have not been able to confirm that this is an inherent limitation in HealthKit's API. Is it a glitch in this plugin?

**Comment by bcfchen** [comment]
we've also seen a similar (not sure if same) issue on an iphone 5s running 8.3. after upgrading to the latest healthkit plugin, the query only returns the past 3 days' data. on another device (iphone 5s running 8.4), it's returning the correct set of past 20 days' data. we're wondering if this might be a OS backwards compatibility issue?

**Comment by H0rst** [comment]
I use it for getting Heartrate. It returns always a maximum of 100 values. But it was easy to make a workaround. I get the 100 newest values. So i check for the lowest date of the result and make another query with this date (one minute less) as enddate. I repeat this, until i get no more values.

**Comment by kingsfleet** [comment]
That is just the default limit, if you look at the source code there is a limit parameter you can override:

https://github.com/Telerik-Verified-Plugins/HealthKit/blob/master/src/ios/HealthKit.m#L645

Sorry I think I forgot to document this.

**Comment by zpeterg** [comment]
H0rst, I did use a workaround like what you describe. It's probably a good idea regardless, in case the results get truncated. Likely Healthkit won't allow endless streams of output anyway.

Kingsfleet, thank you for the pointer! There it is!

**Comment by OleksandrPoltavets** [comment]
I faced the same limitation of 100.
You can set limit to '0' :
`'limit': 0`
this will remove default limitation of 100 and you will receive all data from device
