### ISSUE TITLE
Best place to ask questions + getting data points?

### ISSUE THREAD

**Issue by hdavidzhu** [Telerik-Verified-Plugins/HealthKit#42]
What is the best place to ask general questions about this plugin? I don't want to clutter up the issue box, but I haven't found a good alternative space to ask questions.

(My actual question: ) I've been using the plugin to get my steps for a whole day, but I would like to get the actual step data points to produce my own graph. Currently, I'm using something like this:

```
window.plugins.healthkit.sumQuantityType({
  'startDate': startDate,
  'endDate': endDate,
  'sampleType': 'HKQuantityTypeIdentifierStepCount'
}
```

My `startDate` and `endDate` are defined by moment.  This utilizes `sumQuantityType`, so it only return the sum. How can I get the individual points?

I've been following this tutorial: http://kingsfleet.blogspot.co.uk/2015/02/how-long-did-i-sleep-last-night-using.html

**Comment by hdavidzhu** [comment]
`querySampleType` does what I want! (for the second part of my question - still curious about the first part!). Also, would it be useful to contribute pull request documentation to  `README.md`?

**Comment by EddyVerbruggen** [comment]
Thx for the PR :+1:
