### ISSUE TITLE
Where can I find documentation on units?

### ISSUE THREAD

**Issue by hdavidzhu** [Telerik-Verified-Plugins/HealthKit#44]
Some queries call for a unit attribute, but I'm not sure what exactly is the format of this input. The documentation on Apple follows a `<unitname>Unit` format. What about here? 

Apple developer units here: https://developer.apple.com/library/prerelease/ios/documentation/HealthKit/Reference/HKUnit_Class/index.html#//apple_ref/occ/clm/HKUnit/mileUnit

Is this the [proper list](https://developer.apple.com/library/prerelease/ios/documentation/HealthKit/Reference/HKUnit_Class/index.html#//apple_ref/occ/clm/HKUnit/unitFromString:) of all units possible?

**Comment by EddyVerbruggen** [comment]
Which plugin function are you using and how? Perhaps I can help you with your specific case instead of pointing you at the [Apple docs](https://developer.apple.com/library/ios/documentation/HealthKit/Reference/HKUnit_Class/index.html#//apple_ref/doc/uid/TP40014727-CH1-DontLinkElementID_13).

**Comment by hdavidzhu** [comment]
I was trying to do a `sumQuantityType` or a `queryQuantityType` for `HKQuantityTypeIdentifierDistanceWalkingRunning` and I tried a variety of options for units using things such as `miles`, etc. What I didn't realize is that units utilize a `unitFromString`, and Apple's documentation had a dropdown pop up when you click on a specific section of the documentation. I didn't realize this for the longest time, and whenever I Google an issue or try to find on page, no results show up.

Only after clicking on [this](https://developer.apple.com/library/prerelease/ios/documentation/HealthKit/Reference/HKUnit_Class/index.html#//apple_ref/occ/clm/HKUnit/unitFromString:) did I see a more comprehensive list of all available units and their conversions into HKUnits.

If you're interested, I think I can add some of these links to the `README.md` for easier reference in the future.
