### ISSUE TITLE
Exception with Withings blood pressure data

### ISSUE THREAD

**Issue by H0rst** [Telerik-Verified-Plugins/HealthKit#48]
Hello, 

it sounds weird, but i have a strange issue. I use
```
    window.plugins.healthkit.queryCorrelationType(
        {
			'startDate' : new Date(0), 
			'endDate'   : new Date(), 
			'correlationType': 'HKCorrelationTypeIdentifierBloodPressure', 
			'unit': 'mmHg'
        },
		function (value) {
		alert('alive')
		...
```
This is working. When i add manual values or with the plugin, i can read them. But when i use a Withings blood pressure monitor with the withings app and a single value is added, then i get this exception:

```
2015-08-24 15:00:56.367 BloodPressureTest[225:14006] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (__NSTaggedDate)'
*** First throw call stack:
(0x1861d822c 0x1976240e4 0x1861d816c 0x18714c20c 0x18714e1bc 0x18612c444 0x18611998c 0x18714ddb0 0x18714c0d4 0x18714e1bc 0x18612c444 0x18611998c 0x18714ddb0 0x18714c0d4 0x18714e0a4 0x1860ccd48 0x1860ccc2c 0x18714dfa4 0x18714c178 0x18714e1bc 0x1860c19e0 0x1860c18c0 0x18714ddb0 0x18714c0d4 0x18714e0a4 0x1860ccd48 0x1860ccc2c 0x18714dfa4 0x18714c178 0x18714e0a4 0x1860d3b94 0x1860ca4f4 0x18714dfa4 0x18714c178 0x18714bf00 0x18714cfe8 0x10006f5e4 0x10005c1b8 0x100070730 0x10004d22c 0x100258f94 0x100267a60 0x100258f94 0x10025dc28 0x18618f544 0x18618d5ec 0x1860b8f74 0x18f9bb6fc 0x18acbad94 0x100004ba8 0x197ccea08)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
The alert is not shown. I have tried to play with the dates, but i get always the same result.

Any idea what to do?

**Comment by H0rst** [comment]
More info: 
I have tested with 0.3.5 and 0.3.7. 
My workaround is querying systolic and diastolic with window.plugins.healthkit.querySampleType. 

This works for me. Let me know if i can support finding the issue.

**Comment by sgilroy** [comment]
I was able to resolve this error by checking isValidJSONObject on sample.metadata in queryCorrelationType

https://github.com/TwineHealth/HealthKit/commit/04ba07215989216bf097aae6367003559688eeb6

**Comment by EddyVerbruggen** [comment]
@sgilroy Looks legit. Are you willing to do a little Pull Request for that change?
