### ISSUE TITLE
Should the pluggin name be more generic to support GoogleFit in the future?

### ISSUE THREAD

**Issue by kingsfleet** [Telerik-Verified-Plugins/HealthKit#5]
Google have a similar API:

https://developers.google.com/fit/

It might be worth making sure the designed API is suitably generic so that it could be used for both.

**Comment by gylippus** [comment]
Hey @EddyVerbruggen any thoughts on whether you all are going to take on the separate Google Fit option? Our HealthKit integration has been flawless by the way. Thanks again.

**Comment by EddyVerbruggen** [comment]
Hi, Google Fit is not planned at the moment, but [based on votes](http://telerik-verified-plugins.uservoice.com/forums/258510-plugin-ideas/suggestions/6971244-google-fit) we may consider creating one in the future.

**Comment by gylippus** [comment]
Thanks Eddy. Might give it a go internally or just use their REST API.

**Comment by EddyVerbruggen** [comment]
I'd be very interested in anything you find out on the subject, so don't hesitate to keep me in the loop if you decide to dive into the details.
