### ISSUE TITLE
Healthkit retain cycle error

### ISSUE THREAD

**Issue by mdornellas** [Telerik-Verified-Plugins/HealthKit#50]
I have an app and i'm trying to use HealthKit plugin. Everything works fine (on my device) but i'm unabled to upload it to app store since it gives me an error on 
[self.commandDelegate sendPluginResult:result callbackId:command.callbackId];

The error:
Capturing 'self' strongly in this block is likely to lead to a retain cycle

Do you have any idea how can i resolve this?

Thanks a lot
Martim Dornellas

**Comment by EddyVerbruggen** [comment]
Just tested every supported method again and didn't see this error. Please provide more details (which method is called for instance) if it still persist.
