### ISSUE TITLE
querySampleType does not work with retrieving BAC

### ISSUE THREAD

**Issue by gsccheng** [Telerik-Verified-Plugins/HealthKit#51]
Hi, I am not getting a proper value back with HKQuantityTypeIdentifierBloodAlcoholContent. Although it isn't explicit, the Healthkit docs seem to indicate the `unit` should be `'percent'`. However, that argument, along with other dummy arguments don't seem to be accepted. However, `'count'` is accepted but in my success callback I am not getting a value but an empty array. Is this a bug? Anyone else have this issue? The example given with stepcount works fine for me.

[Here](https://developer.apple.com/library/prerelease/ios/releasenotes/General/iOS80APIDiffs/frameworks/HealthKit.html) is HKTypeIdentifiers.h for your reference.

**Comment by gsccheng** [comment]
Nevermind I have this now. It accepted `%`, perhaps this function can be modified to accept either for the BAC.

**Comment by EddyVerbruggen** [comment]
Makes sense, implemented!
