### ISSUE TITLE
findWorkouts doesn't return bundleIdentifier or workoutActivity

### ISSUE THREAD

**Issue by incentfit** [Telerik-Verified-Plugins/HealthKit#52]
When I query findWorkouts I'm just getting back duration, startDate and endDate.
It appears bundleIdentifier and workoutActivity are not being returned.

Here's the code:

NSMutableDictionary *entry = [[NSMutableDictionary alloc] initWithObjectsAndKeys:
                                          [NSNumber numberWithDouble:workout.duration], @"duration",
                                          [df stringFromDate:workout.startDate], HKPluginKeyStartDate,
                                          [df stringFromDate:workout.endDate], HKPluginKeyEndDate,
                                          workout.source.bundleIdentifier, HKPluginKeySourceBundleId,
                                          workoutActivity, @"activityType",
                                          nil
                                          ];

**Comment by incentfit** [comment]
Also it would seem that the UUID, SourceName and IsUserEntered properties should be available too, as well as metadata.
Would be great to return these.

**Comment by EddyVerbruggen** [comment]
Do you have a documentation reference for the isUserEntered property? I can't seem to find it.

I now have added the UUID and sourceName properties. Please reopen if you can find isUserEntered.

**Comment by incentfit** [comment]
isUserEntered isn't a property, but read this post, it notes how to see if the data came from the Watch or in the App itself.
http://stackoverflow.com/questions/31542921/objective-c-healthkit-identify-if-source-is-from-apple-iphone-or-apple-watch
