### ISSUE TITLE
findWorkouts returns workouts registered only with health app

### ISSUE THREAD

**Issue by dahel** [Telerik-Verified-Plugins/HealthKit#53]
Hi,
I'm not sure if i'm demanding too much, but for now it looks like `findWorkouts` returns only workouts
inserted manually via Health app, i cannot get any workouts tracked by e.g. Endomondo.
Should it also return workouts from third party apps integrated with iOS Health?

Also there is no calories in workout list item, isn't it possible to get this data too?

**Comment by EddyVerbruggen** [comment]
Hi!
If Endomondo writes to HealthKit (I assume you can see its data in the Health app), this plugin should be able to retrieve them. So it may be a bug in the plugin.

**Comment by dahel** [comment]
Ok, i will check it out again soon and give feedback.
Thanks!

**Comment by astanecki** [comment]
Hi, 

I am also working with HK plugin lately and it seems like the same issue. I have been added new training into Endomondo (connected with Apple Health). Next, I tried to parse this activity in my app (connected also to Apple Health). Result is always empty array []. 

As dahel said, findWorkouts works great, but returns only all activites saved from my application. So when I just add new activity by saveWorkout method, I will not get them by findWorkout. 

It would be nice to hear sth new! :v:

**Comment by EddyVerbruggen** [comment]
@astanecki Have you checked the entered data in the Health app? I just installed Endomondo and save a workout manually, but it writes to 'Walking + Running Distance', not to 'Workouts' (no entries show up in the latter).

**Comment by EddyVerbruggen** [comment]
@astanecki this should give you the those 'Walking + Running Distance' entries:

```js
function querySampleType() {
  window.plugins.healthkit.querySampleType(
    {
      'startDate': new Date(new Date().getTime() - 24 * 60 * 60 * 1000), // a day ago
      'endDate': new Date(), // now
      'sampleType': 'HKQuantityTypeIdentifierDistanceWalkingRunning',
      'unit': 'm'
    },
    onSuccess,
    onError
  );
}
```

**Comment by dahel** [comment]
Yes, this works perfectly. 
Thanks Eddy for response.

And thanks for great plugin :).

Closing

**Comment by astanecki** [comment]
@EddyVerbruggen you're right. 

I expected added workouts in response on HKWorkouts.... identifiers. After a while I saw  Apple Health shows manually added workouts from Endomondo in 'Fitness' section (not 'Workouts). It was mainly my problem.

Thanks by your time!
