### ISSUE TITLE
Non-ISO Date Format

### ISSUE THREAD

**Issue by lamuertepeluda** [Telerik-Verified-Plugins/HealthKit#60]
Hi, 
digging into the code I found that you use these weird settings for NSDateFormatter:

```objc
            NSDateFormatter *df = [[NSDateFormatter alloc] init];
            [df setDateFormat:@"yyyy-MM-dd HH:mm:ss"];
```

The above settings generate a date string that results in "Invalid Date" object when passed to JavaScript Date constructor (tested iPhone 5c, iOS 9.2).  
I would **strongly** suggest to adopt ISO 8601 for better compliance with JavaScript Date object, as suggested [in this post](http://stackoverflow.com/questions/16254575/how-do-i-get-iso-8601-date-in-ios).

These settings are working:

```objc
            NSDateFormatter *df = [[NSDateFormatter alloc] init];
            NSLocale *enUSPOSIXLocale = [NSLocale localeWithLocaleIdentifier:@"en_US_POSIX"];
            [df setLocale:enUSPOSIXLocale];
            [df setDateFormat:@"yyyy-MM-dd'T'HH:mm:ssZZZZZ"];
```

This allows for date deserialization in JavaScript with correct time zone:

```javascript
  /* do some query that yields a result with dates */
 var date = new Date(measure.dateStart); //your well formatted date object that interacts with other JS Libraries
```

cheers,

Vito

**Comment by EddyVerbruggen** [comment]
Hey Vito, makes a lot of sense! Would you mind doing it as a PR? If you have time of course.

**Comment by lamuertepeluda** [comment]
Sure! I'll do it this morning when I'm back to office :)

**Comment by dariosalviwork** [comment]
should this be closed now?

**Comment by EddyVerbruggen** [comment]
Yeps, thx.
