### ISSUE TITLE
When using with Ionic Framework, window.plugins.healthkit worked to get steps, $cordovaHealthKit did not.

### ISSUE THREAD

**Issue by euphonious14** [Telerik-Verified-Plugins/HealthKit#68]
Based off of the ngCordova documentation, I attempted to get steps using the following code:

		$cordovaHealthKit.sumQuantityType(
			{
			  'startDate': new Date(new Date().getTime() - 3 * 24 * 60 * 60 * 1000), // three days ago
          	  'endDate': new Date(), // now
              'sampleType': 'HKQuantityTypeIdentifierStepCount'
			},
			function (value) {
				$scope.value = value;
			},
			function (msg) {
				$scope.value = msg;
			}
		);

This never worked. I finally tried:

		window.plugins.healthkit.sumQuantityType(
			{
			  'startDate': new Date(new Date().getTime() - 3 * 24 * 60 * 60 * 1000), // three days ago
          	  'endDate': new Date(), // now
              'sampleType': 'HKQuantityTypeIdentifierStepCount'
			},
			function (value) {
				$scope.value = value;
			},
			function (msg) {
				$scope.value = msg;
			}
		);

And it worked! I'm not exactly sure when to use `$cordovaHealthKit` vs. `window.plugins.healthkit`

I wanted to note this problem here in case it was a bug, or if others come across this issue.

**Comment by EddyVerbruggen** [comment]
Thank you. I think this should be an issue in the ngCordova repo though.
