### ISSUE TITLE
If you are using Apple Watch, do you first need to open the Health App to sync data and then open your cordova app to get the latest data?

### ISSUE THREAD

**Issue by pushparajsamant** [Telerik-Verified-Plugins/HealthKit#69]

**Comment by EddyVerbruggen** [comment]
No idea. Do you know? Or perhaps Google or StackOverflow knows?

**Comment by pushparajsamant** [comment]
I am facing this issue in my app. I dont get the latest data unless I go to the Health App first.

**Comment by EddyVerbruggen** [comment]
I don't see how that's plugin related.
