### ISSUE TITLE
Add support for HKCharacteristic

### ISSUE THREAD

**Issue by dariosalviwork** [Telerik-Verified-Plugins/HealthKit#72]
although we can read gender, blood type and DoB, it would be nice to also save them and also have access to the FitzpatrickSkinType

**Comment by dariosalviwork** [comment]
Oh I didn't know that. Thanks.

**Comment by EddyVerbruggen** [comment]
`FitzpatrickSkinType` has been added in the (just released) 0.5.0 version. Example in the demo folder, but it's pretty trivial.

Also piggybacked the "other" gender return type, not that a lot of people will be missing it..

**Comment by dariosalviwork** [comment]
you never know :smile:
