### ISSUE TITLE
ios10 - Missing parameters in info.plist 

### ISSUE THREAD

**Issue by 80leaves** [Telerik-Verified-Plugins/HealthKit#77]
Not quite sure where exactly it belongs into, but as of iOS 10 following two parameters have to be present in the info.plist 

https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW48

NSHealthShareUsageDescription="A very good reason why I want to read your data."; 
NSHealthUpdateUsageDescription="A very good reason why I want to write data.";

80leaves

**Comment by EddyVerbruggen** [comment]
I added those [a while ago](https://github.com/Telerik-Verified-Plugins/HealthKit/commit/11d659dc5af4410db311f1be63fd64848de86f72), part of release 0.5.1.

**Comment by 80leaves** [comment]
hmm sorry for the trouble, I am running 0.5.1 but I didn't have them in my plist.
