### ISSUE TITLE
Using Ionic Package build service, keys missing from Info.plist

### ISSUE THREAD

**Issue by marcovtwout** [Telerik-Verified-Plugins/HealthKit#95]
When using the Ionic Package cloud service to build the app, config.xml is configured correctly, but the values are missing from Info.plist. See: https://github.com/dariosalvi78/cordova-plugin-health/issues/86

The solution is here: https://github.com/dariosalvi78/cordova-plugin-health/issues/86#issuecomment-342855633

Could this be added to the README?

**Comment by EddyVerbruggen** [comment]
Sounds to me it's quite a generic issue with Ionic Cloud so it's better to document it there, but if you want to send a PR to add it to the readme I'll probably merge it anyway.

**Comment by marcovtwout** [comment]
Thanks!
